### ISSUE TITLE
使用的是 go mod ，运行报错

### ISSUE THREAD

**Issue by pihc** [snowlyg/IrisApiProject#12]
报错信息：
`routes/route.go:21:20: cannot use crs (type "github.com/kataras/iris/v12/context".Handler) as type "github.com/kataras/iris/context".Handler in argument to api.APIBuilder.Party
routes/route.go:28:23: cannot use crs (type "github.com/kataras/iris/v12/context".Handler) as type "github.com/kataras/iris/context".Handler in argument to api.APIBuilder.Party
routes/route.go:33:18: cannot use crs (type "github.com/kataras/iris/v12/context".Handler) as type "github.com/kataras/iris/context".Handler in argument to api.APIBuilder.Party
routes/route.go:38:37: cannot use middleware.JwtHandler().Serve (type func("github.com/kataras/iris/v12/context".Context)) as type "github.com/kataras/iris/context".Handler in argument to admin.Use
`

我尝试着去把 iris 改成 v12 运行也会报错

1. clone项目，go.mod没有clone下来，遂执行

`  go mod init IrisApiProject `

2. copy您的项目里的go.mod 然后执行

`  go mod tidy`

3. 上面两步都没有问题，然后执行
`go run main.go`

然后就报错了

**Comment by snowlyg** [comment]
好的，我有空看一下

**Comment by snowlyg** [comment]
@pihc 你尝试将 iris 升级到 v12 ，或者克隆本项目的 1.0 版本
