### ISSUE TITLE
前端代码请求发起两次

### ISSUE THREAD

**Issue by 403605209** [snowlyg/IrisApiProject#15]
每次发起请求都会发起两次,第一次不带Authorization,第二次带Authorization.

控制台报错:
vue.esm.js:1741 TypeError: Cannot read property 'orders' of undefined
PermissionsMange.vue:155 Uncaught (in promise) TypeError: Cannot read property 'pageSize' of undefined

**Comment by snowlyg** [comment]
这个前端只是为了演示 api 效果，你可以用自己实现前端
