### ISSUE TITLE
没有使用redis缓存

### ISSUE THREAD

**Issue by 403605209** [snowlyg/IrisApiProject#16]
我看了下代码，好像没有用到redis，实际jwt信息是存在mysql里的，redis里空荡荡的。

**Comment by snowlyg** [comment]
是的，只是集成了redis.的功能！并没有是用！

**Comment by 403605209** [comment]
> 是的，只是集成了redis.的功能！并没有使用！

这个Iris + Vue + mysql + redis + jwt的标题让我误解了

**Comment by snowlyg** [comment]
😂这个项目也是我练手的项目，那时候刚学go写的！
