### ISSUE TITLE
测试不通过

### ISSUE THREAD

**Issue by nagaame** [snowlyg/IrisApiProject#2]
运行`go test -v` 没有通过呢, 好像有类型错误的问题

系统macOS
golang版本 1.12

`# IrisApiProject [IrisApiProject.test]
./base_test.go:175:30: cannot use testPerms (type []"IrisApiProject/models".Permission) as type []uint in argument to "IrisApiProject/models".CreateRole
FAIL    IrisApiProject [build failed]
`

**Comment by snowlyg** [comment]
@nagaame 问题已经修书改
